# Generated by Django 3.1.4 on 2021-01-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerDetatils',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=512)),
                ('address', models.CharField(max_length=1000)),
                ('dob', models.DateField()),
                ('company', models.CharField(max_length=50)),
            ],
        ),
    ]
