# Generated by Django 3.1.4 on 2021-01-03 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptionAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionDetatils',
            fields=[
                ('sub_id', models.IntegerField(primary_key=True, serialize=False)),
                ('subscription_name', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='managerdetatils',
            name='id',
        ),
        migrations.AlterField(
            model_name='managerdetatils',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=17)),
                ('amount', models.IntegerField()),
                ('date_time', models.DateTimeField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptionAPI.managerdetatils')),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptionAPI.subscriptiondetatils')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=17)),
                ('expire_month', models.CharField(max_length=2)),
                ('expire_year', models.CharField(max_length=2)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptionAPI.managerdetatils')),
            ],
        ),
    ]
