# Generated by Django 3.1.4 on 2021-01-03 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptionAPI', '0002_auto_20210103_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptionAPI.managerdetatils'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='sub_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptionAPI.subscriptiondetatils'),
        ),
    ]
