# Generated by Django 2.0.2 on 2021-01-05 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptionAPI', '0002_auto_20210104_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetails',
            name='email',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='email',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='sub_id',
        ),
        migrations.DeleteModel(
            name='PaymentDetails',
        ),
        migrations.DeleteModel(
            name='PaymentHistory',
        ),
    ]
