# Generated by Django 2.0.2 on 2021-01-05 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptionAPI', '0003_auto_20210105_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptionAPI.ManagerDetails')),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptionAPI.SubscriptionDetails')),
            ],
        ),
    ]
